// Mocks generated by Mockito 5.4.6 from annotations
// in koto_tinder/test/liked_cats_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:koto_tinder/domain/entities/cat.dart' as _i5;
import 'package:koto_tinder/domain/repositories/cat_repository.dart' as _i2;
import 'package:koto_tinder/domain/usecases/get_breeds.dart' as _i7;
import 'package:koto_tinder/domain/usecases/get_liked_cats.dart' as _i3;
import 'package:koto_tinder/domain/usecases/remove_liked_cat.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCatRepository_0 extends _i1.SmartFake implements _i2.CatRepository {
  _FakeCatRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetLikedCatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLikedCatsUseCase extends _i1.Mock
    implements _i3.GetLikedCatsUseCase {
  MockGetLikedCatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatRepository get catRepository =>
      (super.noSuchMethod(
            Invocation.getter(#catRepository),
            returnValue: _FakeCatRepository_0(
              this,
              Invocation.getter(#catRepository),
            ),
          )
          as _i2.CatRepository);

  @override
  _i4.Future<List<_i5.Cat>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<List<_i5.Cat>>.value(<_i5.Cat>[]),
          )
          as _i4.Future<List<_i5.Cat>>);

  @override
  _i4.Future<List<_i5.Cat>> executeByBreed(String? breed) =>
      (super.noSuchMethod(
            Invocation.method(#executeByBreed, [breed]),
            returnValue: _i4.Future<List<_i5.Cat>>.value(<_i5.Cat>[]),
          )
          as _i4.Future<List<_i5.Cat>>);
}

/// A class which mocks [RemoveLikedCatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveLikedCatUseCase extends _i1.Mock
    implements _i6.RemoveLikedCatUseCase {
  MockRemoveLikedCatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatRepository get catRepository =>
      (super.noSuchMethod(
            Invocation.getter(#catRepository),
            returnValue: _FakeCatRepository_0(
              this,
              Invocation.getter(#catRepository),
            ),
          )
          as _i2.CatRepository);

  @override
  _i4.Future<void> execute(String? catId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [catId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GetBreedsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBreedsUseCase extends _i1.Mock implements _i7.GetBreedsUseCase {
  MockGetBreedsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatRepository get catRepository =>
      (super.noSuchMethod(
            Invocation.getter(#catRepository),
            returnValue: _FakeCatRepository_0(
              this,
              Invocation.getter(#catRepository),
            ),
          )
          as _i2.CatRepository);

  @override
  _i4.Future<List<String>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> executeFromLikedCats() =>
      (super.noSuchMethod(
            Invocation.method(#executeFromLikedCats, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);
}
