name: koto_tinder
description: "A new Flutter project."
publish_to: 'none'
version: 3.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.3

  # Зависимости для дз №2
  get_it: ^7.6.4 # DI (внедрение зависимостей)
  flutter_bloc: ^8.1.3 # Для управления состоянием
  intl: ^0.19.0 # Для форматирования даты

  # Новые зависимости для дз №3
  sqflite: ^2.3.0 # SQLite для локального хранения
  connectivity_plus: ^4.0.2 # Проверка сети (старая версия)
  path: ^1.8.3 # Для работы с путями к файлам
  shared_preferences: ^2.2.2 # Для счетчика лайков
  dio: ^5.4.0 # Для загрузки изображений
  path_provider: ^2.1.2 # Для доступа к файловой системе
  crypto: ^3.0.3 # Для генерации хэшей

  # Для темной темы
  provider: ^6.1.1 # Управление состоянием темы

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

  # Зависимости для тестирования
  mockito: ^5.4.4 # Мокирование
  build_runner: ^2.4.7 # Для генерации моков
  bloc_test: ^9.1.5 # Тестирование BLoC

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/cat_icon.png"
  adaptive_icon_background: "#F5E9FF"
  adaptive_icon_foreground: "assets/icon/cat_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/